### ISSUE TITLE
3.3.2: Create From Folder unsanitized leading directory separators

### ISSUE THREAD

**Issue by Rythyrix** [craftablescience/VPKEdit#10]
On Windows, when using the Create From Folder option, entries of the directory tree have leading directory separators.

This causes L4D2 (at least), to not load resources present in the created VPK, despite data being present and correct in VPK.

This issue does not occur with adding files one at a time.

Screenshots:
3.3.2 output:
![3.3.2](https://github.com/craftablescience/VPKEdit/assets/9667057/c2e41cae-c4ae-49fd-92f3-7d3a25d6cbe3)

Proposed output:
![Corrected](https://github.com/craftablescience/VPKEdit/assets/9667057/62203e07-ee49-48dc-9201-16b3e8aa4b27)

**Comment by craftablescience** [comment]
Thanks for fixing this, stupid oversight on my part
