### ISSUE TITLE
vpkedit fails to open (Ubuntu Linux)

### ISSUE THREAD

**Issue by mrhoomanwastaken** [craftablescience/VPKEdit#106]
### Describe the Bug

after attempting to open vpk edit from my app selector, it fails to do anything. it does not display any errors or open anything. 
system info:
Ubuntu Linux 23.10(latest)
used Gdebi package installer to install vpkedit

### To Reproduce

1. download the latest ver of vpkedit installer
2. use gdebi (or possibly apt as I have not tried) to install
3. go to the app selector and open vpkedit

### Operating System

Ubuntu Linux 23.10

**Comment by mrhoomanwastaken** [comment]
I just tried using apt and it through an error.

N: Download is performed unsandboxed as root as file '/home/mrhooman/Downloads/VPKEdit-4.0.1-Linux.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

Note: I was using sudo

**Comment by craftablescience** [comment]
This "error" happens on my machine too, it works completely fine and you can ignore it

**Comment by craftablescience** [comment]
Sorry, forgot that wasnt the entire issue

**Comment by mrhoomanwastaken** [comment]
I just tried following the instructions from here [https://craftablescience.info/ppa/ ](https://craftablescience.info/ppa/ 
) 
it did not put up an error but it still will not open.

**Comment by mrhoomanwastaken** [comment]
sorry im on a trip but i will do it when i get home on Sunday!

**Comment by mrhoomanwastaken** [comment]
When I run `vpkedit` it says

> qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this 
> problem.

> Available platform plugins are: linuxfb, xcb, vnc, wayland-egl, minimal, vkkhrdisplay, wayland, minimalegl, eglfs, offscreen.

> Aborted (core dumped)

I will find the core dump if you need it.

ps.sorry for the bad formatting, I'm still newish to making issues on GitHub

**Comment by craftablescience** [comment]
>  xcb-cursor0 or libxcb-cursor0

Have you tried installing this library?

**Comment by craftablescience** [comment]
Installing this library seems to fix the issue for other people, please reopen if it doesn't solve the problem for you

**Comment by mrhoomanwastaken** [comment]
That fixes it, thanks!
