### ISSUE TITLE
Add install commands for C wrapper library

### ISSUE THREAD

**Issue by HurricanePootis** [craftablescience/VPKEdit#109]
### Describe the Bug

Whenever I enable the CMake flag `-DVPKEDIT_BUILD_LIBC`, I get the following error [here](https://gist.github.com/HurricanePootis/c468c869416c7455cc6bc9abdae7974b). [Here](https://gist.github.com/HurricanePootis/f091b35fa843ffd04158c5faeded832e) is the one for clang.

This is on the latest release 4.1.0.

### To Reproduce

```
#!/bin/bash

git clone --recursive https://github.com/craftablescience/VPKEdit.git
cd VPKEdit
cmake -B build -S ./ -DCMAKE_BUILD_TYPE=Release -DVPKEDIT_BUILD_LIBC=ON
cmake --build build
```

### Operating System

Arch Linux

**Comment by craftablescience** [comment]
Sorry, I guess I forgot to define that for Linux... one sec

**Comment by craftablescience** [comment]
Should be fixed now, lmk if there's any other issues

**Comment by HurricanePootis** [comment]
A lot of the errors have been fixed, but I am now getting this new error
```
/home/hurricane/vpkedit/src/vpkedit/src/libc/Helpers.cpp: In function ‘std::size_t writeStringToBuffer(std::string_view, char*, std::size_t)’:
/home/hurricane/vpkedit/src/vpkedit/src/libc/Helpers.cpp:17:22: error: ‘memcpy’ is not a member of ‘std’; did you mean ‘wmemcpy’?
   17 |                 std::memcpy(buffer, str.data(), bufferLen);
      |                      ^~~~~~
      |                      wmemcpy
/home/hurricane/vpkedit/src/vpkedit/src/libc/Helpers.cpp:21:14: error: ‘memcpy’ is not a member of ‘std’; did you mean ‘wmemcpy’?
   21 |         std::memcpy(buffer, str.data(), str.length());
      |              ^~~~~~
      |              wmemcpy
/home/hurricane/vpkedit/src/vpkedit/src/libc/Helpers.cpp: In function ‘std::size_t writeVectorToBuffer(const std::vector<std::byte>&, unsigned char*, std::size_t)’:
/home/hurricane/vpkedit/src/vpkedit/src/libc/Helpers.cpp:28:22: error: ‘memcpy’ is not a member of ‘std’; did you mean ‘wmemcpy’?
   28 |                 std::memcpy(buffer, vec.data(), bufferLen);
      |                      ^~~~~~
      |                      wmemcpy
/home/hurricane/vpkedit/src/vpkedit/src/libc/Helpers.cpp:31:14: error: ‘memcpy’ is not a member of ‘std’; did you mean ‘wmemcpy’?
   31 |         std::memcpy(buffer, vec.data(), vec.size());
      |              ^~~~~~
      |              wmemcpy
/home/hurricane/vpkedit/src/vpkedit/src/libc/Helpers.cpp: In function ‘VPKEdit_StringArray_t convertStringVector(const std::vector<std::__cxx11::basic_string<char> >&)’:
/home/hurricane/vpkedit/src/vpkedit/src/libc/Helpers.cpp:39:22: error: ‘memcpy’ is not a member of ‘std’; did you mean ‘wmemcpy’?
   39 |                 std::memcpy(array.data[i], stringVec[i].c_str(), stringVec[i].length());
      |                      ^~~~~~
      |                      wmemcpy
      ```

**Comment by craftablescience** [comment]
Pushed a commit that should fix that, I'm also going to add this target to CI so it tells me when its broken lol

**Comment by HurricanePootis** [comment]
It builds now! I just got one more question: libvpkeditc.so ain't installed whenever invoking the install command, and are there any header files for the library? I am asking because I am going to be packaging this in the AUR as a split-package with vpkedit.

**Comment by craftablescience** [comment]
> libvpkeditc.so ain't installed whenever invoking the install command

I'll look into fixing this, in the meantime header files are under `include/vpkeditc`

**Comment by HurricanePootis** [comment]
Also, one more thing (sorry), the resulting library is named `liblibvpkeditc.so` in the `build/` directory.

**Comment by craftablescience** [comment]
I think I can fix this, I'll have to pull out my Linux machine to test it though. I'm playing Donut County rn, I'll get to that in about an hour probably

**Comment by HurricanePootis** [comment]
lol enjoy your donut country 🍩🍩🍩🍩

**Comment by craftablescience** [comment]
thx! I fixed the duplicated lib, but I'm not sure how to get the install command to work. It's probably super simple and I'm dumb, but I'm stopping here for the night

**Comment by craftablescience** [comment]
Closing as the C library has now been moved to sourcepp
