### ISSUE TITLE
CTX decompiler (vice)

### ISSUE THREAD

**Issue by ghost** [craftablescience/VPKEdit#111]
### Describe Your Suggestion

would be cool to be able to integrate vice into it, so that I don't have to extract the entire vpk, decompile that one file, edit it, recompile it again, and pack the vpk again. [here's a link to some vice keys](https://wiki.alliedmods.net/Vice_keys). [and here's vice standalone, which doesn't require steam (works in arch too!)](https://github.com/foobarhl/vice_standalone)

**Comment by craftablescience** [comment]
Yeah this is pretty sick

https://github.com/user-attachments/assets/8eccfbc2-83e6-450f-b643-e564028c4565
