### ISSUE TITLE
Can't open .FPX files.

### ISSUE THREAD

**Issue by mrwallace888** [craftablescience/VPKEdit#114]
### Describe the Bug

Was wanting to extract stuff from that old game Tactical Intervention. I saw that .FPX support was added to this for 4.1, but when attempting to open any of the files, it just says "Unable to load this file. Please ensure that a game or another application is not using the file."

### To Reproduce

1. Open VPKEdit.
2. Select any of Tactical Intervention's .FPX files or _fdr.FPX.
3. Profit(?)

### Operating System

Windows 10 Pro

**Comment by craftablescience** [comment]
I'm really stupid, FPX files are very similar to VPK files and it's trying to use the VPK parser. Sorry about that!

**Comment by craftablescience** [comment]
Update to 4.1.2, it should work now
