### ISSUE TITLE
Remember last folder for file open/save dialogs

### ISSUE THREAD

**Issue by vrad-exe** [craftablescience/VPKEdit#116]
### Describe Your Suggestion

File open/save dialogs should remember the last selected folder, and start there the next time one is opened.

**Comment by craftablescience** [comment]
Actually I'm not sure what you're asking? This functionality already seems to work on both operating systems

**Comment by vrad-exe** [comment]
I think I meant across restarts? Or maybe it's just one specific case where it doesn't work - when you use "create VPK from folder", it defaults to the VPKEdit install directory for *both* of the file selection prompts that appear, when I would expect the first to default to the last opened folder (including across restarts) and the second to default to the location selected in the first.

**Comment by vrad-exe** [comment]
Why can't you save it across restarts?

**Comment by vrad-exe** [comment]
Strata Hammer does it

**Comment by craftablescience** [comment]
They do the thing that I was referring to that takes a ton of effort, saving every last known path per dialog to the settings

**Comment by craftablescience** [comment]
I have a lot of dialogs
