### ISSUE TITLE
Wont open in linux (LM Virginia/ubuntu jammy

### ISSUE THREAD

**Issue by superstarx** [craftablescience/VPKEdit#117]
### Describe the Bug

When I open/launch the program it spits out an error, I've tried different releases and versions but it keeps happening. I am aware that there's a few other issues about this but they did not help me.
here's the output (which is think is virtually the same with the other versions):

```
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: offscreen, vkkhrdisplay, minimalegl, eglfs, vnc, linuxfb, minimal, wayland-egl, xcb, wayland.

Aborted (core dumped)
```

### To Reproduce

1. launch from terminal
2. error

### Operating System

Linux - LM virginia

**Comment by craftablescience** [comment]
This seems to be an issue with Ubuntu in general, I get the same error in WSL. I'll look into it

**Comment by craftablescience** [comment]
Have you tried:
`sudo apt install libxcb-cursor0`

**Comment by superstarx** [comment]
This seems to work, not sure if I had tried this already, but thanks still!
