### ISSUE TITLE
Animated VTFs skip the first frame and duplicate the last frame

### ISSUE THREAD

**Issue by vrad-exe** [craftablescience/VPKEdit#125]
### Describe the Bug

When viewing an animated VTF, the first frame appears to be skipped and the last frame appears to be listed twice. Specifically I noticed this with Portal 2's `materials/vgui/spinner.vtf`

### To Reproduce

1. Open an animated VTF like the one above
2. Click through the frames of the animation

### Operating System

Tested on Windows 10

**Comment by craftablescience** [comment]
Thanks for making this issue, not only was there an off-by-one error on both the face and frame spinners I also found out the face spinner was completely nonfunctional
