### ISSUE TITLE
Add support for signing VPKs with a private key

### ISSUE THREAD

**Issue by chloecormier** [craftablescience/VPKEdit#130]
### Describe Your Suggestion

Valve's VPK tool allows the user to generate a key-pair, use the private key to sign a set of VPKs, and verify VPKs using a public key. This is relevant for multiplayer Source games which enforce sv_pure by shipping with a list of trusted public keys, and then signing their VPKs with the project's private key.

When using vpkeditcli to automate VPK generation, being unable to sign VPKs with a private key makes it impossible to use in production without breaking sv_pure. Implementing this would close the gap with vpk.exe for my project, and allow for a heavily streamlined release pipeline.

**Comment by craftablescience** [comment]
VPKs can now be signed with the `-k` / `--sign` parameter, which takes a path to the private key file. This file uses the same format as the official Valve VPK tool for compatibility, but if you don't have one you can generate one with `vpkeditcli --gen-keypair <name>`. Hope this helps and please make another issue if it's not working correctly for you!
