### ISSUE TITLE
Flattened Cubemap view

### ISSUE THREAD

**Issue by JasperCarmack** [craftablescience/VPKEdit#135]
### Describe Your Suggestion

The ability to see all 6 of the cubemap faces in a preview would be nice, especially for debugging cubemap renders/searching for issues with rendered cubemaps. That way a user doesn't have to manually set the face number to see each one. A similar approach could be used for skyboxes to see how they look unwrapped.

![CubeMapPreview](https://github.com/craftablescience/VPKEdit/assets/104959598/6b056bd6-9ddf-4f51-a905-d6b7989af6bd)

**Comment by NvC-DmN-CH** [comment]
Kinda related, but it would be cool for cubemaps/skyboxes to be easily editable with tools like these but local:

https://jaxry.github.io/panorama-to-cubemap/

https://danilw.github.io/GLSL-howto/cubemap_to_panorama_js/cubemap_to_panorama.html

**Comment by craftablescience** [comment]
Going to make another issue with the relevant skybox stuff
