### ISSUE TITLE
Default Qt project file is used

### ISSUE THREAD

**Issue by Tiagoquix** [craftablescience/VPKEdit#138]
### Describe the Bug

I noticed that the program seems to use a default Qt project file (`~/.config/QtProject.conf`).

I would suggest moving the file to its own folder (`~/.config/VPKEdit/QtProject.conf`) to avoid conflicts with other programs.

Thanks in advance.

### To Reproduce

Explained above.

### Operating System

Fedora Linux 40 KDE

**Comment by craftablescience** [comment]
What conflicts could come up? I'm not sure what the utility of that config file is. You can override the location with an environment variable, `XDG_CONFIG_HOME`

**Comment by craftablescience** [comment]
What does it actually do, store QSettings information? I don't really see why that has to be stored in a separate file, and don't even know how I would go about implementing this

**Comment by craftablescience** [comment]
I see zero reason to modify where this file is stored universally then. If you want to modify it for your install use the environment variable I mentioned
