### ISSUE TITLE
Change file picker to the one used by the system

### ISSUE THREAD

**Issue by Tiagoquix** [craftablescience/VPKEdit#140]
### Describe Your Suggestion

Hi there.

From what it looks like, VPKEdit uses its own file picker instead of making a call to show the system one.

For example, I can confirm that the one used in VPKEdit is not from KDE itself and therefore does not display my common shortcuts that I have.

I suggest that there be some way to use the system file picker (probably by specifying something generic with XDG, but I don't know the technical details of the implementation).

I'm on Fedora Linux 40 KDE.

Thanks in advance.

**Comment by craftablescience** [comment]
This won't be implemented, I will continue to use the Qt file picker. If Qt doesn't use your native file dialog, maybe that's #93 rearing its head again.
