### ISSUE TITLE
Save failure dialog always assumes the loaded file is a VPK

### ISSUE THREAD

**Issue by Trico-Everfire** [craftablescience/VPKEdit#145]
### Describe the Bug

![image](https://github.com/craftablescience/VPKEdit/assets/55441008/14d5b589-5a61-427d-bb05-2be5fb01d777)

### To Reproduce

Open a BSP
make sure it cannot write the bsp
it tells you it could not save the VPK.

### Operating System

N/A

**Comment by craftablescience** [comment]
Never updated this line when support for more formats was added
