### ISSUE TITLE
CLI tool reading support

### ISSUE THREAD

**Issue by NvC-DmN-CH** [craftablescience/VPKEdit#148]
### Describe Your Suggestion

Just making this to let it be known that there is at least some demand for this feature

**Comment by craftablescience** [comment]
Understood, I'll get this done in the next major release :+1:

Still going to mark this as a duplicate of #43 though lol

**Comment by NvC-DmN-CH** [comment]
> Understood, I'll get this done in the next major release 👍
> 
> Still going to mark this as a duplicate of #43 though lol

oh okay

By the way I'm working on something right now and a CLI version of your tool will be super massively appreciated, cause i saw the vdc page for the vpk file format and i got instantly overwhelmed lol
