### ISSUE TITLE
Show entry context menu in directory preview

### ISSUE THREAD

**Issue by BreakinBenny** [craftablescience/VPKEdit#15]
In its current state, VPKEdit can't extract select files from a package unlike GCFScape. Any thoughts on allowing something akin to that?

**Comment by craftablescience** [comment]
Right click the file in the tree in the left pane

**Comment by BreakinBenny** [comment]
> Right click the file in the tree in the left pane

OK nice, thanks!

**Comment by craftablescience** [comment]
I'm going to rename this issue to be about having that context menu pop up in the directory preview widget as well

**Comment by BreakinBenny** [comment]
> I'm going to rename this issue to be about having that context menu pop up in the directory preview widget as well

I won't lie, I didn't know it was possible to extract the stuff like that.

**Comment by craftablescience** [comment]
GCFScape extracts individual files and folders the same way, except it shows the context menu in the central pane and not the left tree

**Comment by BreakinBenny** [comment]
Have there been thoughts on allowing to open Source BSPs too, come to think of it?

**Comment by craftablescience** [comment]
I've thought of it, it wouldn't be easy though. Might happen someday but don't count on it

**Comment by BreakinBenny** [comment]
Just thinking it would be decent for obsoleting GCFScape overall, but then again I may as well go for BSPZIP instead.
