### ISSUE TITLE
Add a support for a Steam that is installed as Snap Package

### ISSUE THREAD

**Issue by Sectonidse** [craftablescience/VPKEdit#151]
### Describe the Bug

I'm not really sure if that's a bug or a feature request though.
So here what happens:
1. The User launches VPKEdit
2. VPKEdit looks up for a libraryfolders.vdf
3. bad things happen
What went wrong:
- The Steam was installed as a Snap package
- All the Snap packages are located in [ROOT]/snap/ folder
- The VPKEdit's shortcut to libraryfolders.vdf stops at ~/.steam/, where the expected "steam" shortcut is umm... this: 
![image](https://github.com/craftablescience/VPKEdit/assets/94748461/35c30379-7507-4579-af65-df9e3c24781e)
However, you may ignore the shortcut one since it's a remnant of an old Linux installation where Steam was installed as DEB package.

The log:
```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot get file size: Not a directory [/home/Sectonidse/.steam/steam/steamapps/libraryfolders.vdf]
Aborted (core dumped)
```

How to fix it (in code's algorithm):
1. Locate the libraryfolders.vdf the standard DEB way.
If 1 fails, proceed to 2, otherwise continue initializing program.
2. Locate the libraryfolders.vdf in ~/snap/steam/common/.local/share/Steam/steamapps (Snap way)
If 2 fails, show an error message (`zenity --error --text="Unable to boot VPKEdit. Make sure you have Steam installed as a Debian or Snap package." --icon=vpkedit`) otherwise continue initializing program.

### To Reproduce

0. Have Steam as a Snap package.
1. open vpkedit
2. done

### Operating System

Linux Ubuntu 24.04, VPKEdit 4.2.1

**Comment by craftablescience** [comment]
Oops

**Comment by craftablescience** [comment]
I actually can't replicate this crash, I think it's because your old install is messing with the Steam install detection code. Still a bug that I will fix, as well as it not finding the snap install
