### ISSUE TITLE
Incomplete Steam installations cause fatal crash (4.2.1+)

### ISSUE THREAD

**Issue by dfhjgjlyordy6t** [craftablescience/VPKEdit#152]
### Describe the Bug

So basically the title. The vpkedit latest version doesn't run at all, not even for a second and only versions that are 4.2.0 and less work. I use windows 10 22H2.

### To Reproduce

1. Install VPKEdit 4.2.1
2. Run VPKEdit
3. Doesn't open

### Operating System

Windows 10 22H2

**Comment by craftablescience** [comment]
I'll look into this right away

**Comment by dfhjgjlyordy6t** [comment]
> I'll look into this right away

Alright

**Comment by dfhjgjlyordy6t** [comment]
Releated to vpkedit.exe, don't know why i specified it since i think it's kind of obvious and it feels kinda weird to say it but it may help. That's because i've got the standalone download of 4.2.1 and replaced all of the files of 4.2.0 until i got to vpkedit.exe and when i replaced the vpkedit.exe it stopped working.

**Comment by caatge** [comment]
![image](https://github.com/craftablescience/VPKEdit/assets/99887872/ddd39184-1920-4dd9-a7c5-bccf1f7546e0)
Maybe you're missing VC Redist? (https://aka.ms/vs/17/release/vc_redist.x64.exe)

**Comment by craftablescience** [comment]
I can't reproduce this either, I have a suspicion it's related to a change I made to a third-party library. Did you by chance have Steam installed and later uninstalled it, or installed Steam but had Steam closed when opening VPKEdit?

**Comment by dfhjgjlyordy6t** [comment]
> I can't reproduce this either, I have a suspicion it's related to a change I made to a third-party library. Did you by chance have Steam installed and later uninstalled it, or installed Steam but had Steam closed when opening VPKEdit?

I use 7launcher (a counter-strike: source launcher) to play the game. And yes i had steam at some point but i uninstalled it since most of the time i download it temporarily to play a game and then uninstall it. I will try to install steam. put the counter-strike: source executable file into steam (you can do it since there's a function to put non steam games on steam on your library and it actually adds counter-strike: source (steam version) in your library but it shows something like "buy" instead of run). But this also happens when i don't use 7launcher.

**Comment by dfhjgjlyordy6t** [comment]
Someone said to install vc redist so i will try

**Comment by dfhjgjlyordy6t** [comment]
I can't install steam rn (it's night for me) so i will do it tommorow and share my results.

**Comment by craftablescience** [comment]
Try this standalone build: 
[VPKEdit-Windows-Standalone-GUI-msvc-Release.zip](https://github.com/user-attachments/files/15523011/VPKEdit-Windows-Standalone-GUI-msvc-Release.zip)

**Comment by dfhjgjlyordy6t** [comment]
Already have vc redist installed

**Comment by dfhjgjlyordy6t** [comment]
> Try this standalone build: [VPKEdit-Windows-Standalone-GUI-msvc-Release.zip](https://github.com/user-attachments/files/15523011/VPKEdit-Windows-Standalone-GUI-msvc-Release.zip)

Doesn't work

**Comment by dfhjgjlyordy6t** [comment]
Read my other comments for a little bit more context if you haven't done it already

**Comment by craftablescience** [comment]
That was fast. I'll keep working on the Steam detection reliability

**Comment by dfhjgjlyordy6t** [comment]
> That was fast. I'll keep working on the Steam detection reliability

Alright. Is that something releated to vpkedit or something else, just curious.

**Comment by dfhjgjlyordy6t** [comment]
Maybe i can install steam but without installing counter-strike: source, will try

**Comment by craftablescience** [comment]
I used to use [this library directly](https://github.com/Trico-Everfire/SteamAppPathProvider), I recently switched to a custom fork to add some features I wanted, and I rewrote part of the Steam detection code. Seems like I introduced a bug or two

**Comment by dfhjgjlyordy6t** [comment]
> I used to use [this library directly](https://github.com/Trico-Everfire/SteamAppPathProvider), I recently switched to a custom fork to add some features I wanted, and I rewrote part of the Steam detection code. Seems like I introduced a bug or two

"Steam detection code" Mhmmmmm, kinda implies that i have to install steam, will tell you the results. I don't know if it's exactly what i think but who knows, might fix the problem and save you time.

**Comment by craftablescience** [comment]
I think I've identified the problem, and you won't need Steam installed to use this program, don't worry

**Comment by dfhjgjlyordy6t** [comment]
> I think I've identified the problem, and you won't need Steam installed to use this program, don't worry

Alright, what's the problem then? I know you said "i think" but just curious to what you indentified

**Comment by craftablescience** [comment]
From the vpkedit discord channel:
![image](https://github.com/craftablescience/VPKEdit/assets/26600014/260c8ec4-c825-403e-ae20-b933fecf2ab0)

shoutout to bt for debugging this

**Comment by dfhjgjlyordy6t** [comment]
> From the vpkedit discord channel: ![image](https://private-user-images.githubusercontent.com/26600014/335823616-260c8ec4-c825-403e-ae20-b933fecf2ab0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNzAxMDcsIm5iZiI6MTcxNzI2OTgwNywicGF0aCI6Ii8yNjYwMDAxNC8zMzU4MjM2MTYtMjYwYzhlYzQtYzgyNS00MDNlLWFlMjAtYjkzM2ZlY2YyYWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE5MjMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NWU1YWZlOTJmOWFlNDFkYzM1MDM1MGJjOWZlYjQzNTg4OWE4M2JmMmZmNDVhM2VlNmVkZTJlZTIwOWM5ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cIsJ8kUgen6N8TK4qw6MpzsSPv4-E0LpM_xlmC3A07A)
> 
> shoutout to bt for debugging this

Makes sense. If you fixed it then tell me.

**Comment by dfhjgjlyordy6t** [comment]
Yep it's releated to steam and so the thing that bt debugged.

**Comment by craftablescience** [comment]
When you're back at your PC, try this build:
[VPKEdit-Windows-Standalone-GUI-msvc-Release(1).zip](https://github.com/user-attachments/files/15523163/VPKEdit-Windows-Standalone-GUI-msvc-Release.1.zip)

**Comment by dfhjgjlyordy6t** [comment]
> When you're back at your PC, try this build: [VPKEdit-Windows-Standalone-GUI-msvc-Release(1).zip](https://github.com/user-attachments/files/15523163/VPKEdit-Windows-Standalone-GUI-msvc-Release.1.zip)

It works!

**Comment by craftablescience** [comment]
Perfect, sorry for the trouble

I'll push a hotfix release soon

**Comment by dfhjgjlyordy6t** [comment]
> Perfect, sorry for the trouble
> 
> I'll push a hotfix release soon

Alright
