### ISSUE TITLE
TF2: Opening a VTF file that was once open makes it no longer open

### ISSUE THREAD

**Issue by logslmao** [craftablescience/VPKEdit#155]
### Describe the Bug

When i try to open the file, it says that programs are using it but they arent as tf2 is closed and the files are in a different directory

### To Reproduce

1. Try to open the app.
2. It wont open

### Operating System

Linux Mint (Ubuntu Based)

**Comment by craftablescience** [comment]
So if I'm reading the title right, this happens if you open a VPK, close it, and then open it again?

**Comment by logslmao** [comment]
No? If i take a vtf from the currently loaded sprays folder in tf2, close tf2 and try to open the sprays i saved (tf2 auto deletes sprays once the game closes) they dont open

**Comment by 1resubuhtig** [comment]
I have a similar issue, but I'm on Windows and i VPKEdit just wont open, not even vpks wont open.

**Comment by craftablescience** [comment]
I don't know how to reproduce this, if you provide clearer instructions that I can follow on my own PC I'll reopen the issue.

**Comment by logslmao** [comment]
Okay look, i know im REALLY late but i finally got around to recording what happens. Basically, if i take a spray out of the 'temp' folder in tf2 and then close tf2 and try to open it, it refuses to open
[2024-07-24 01-59-04.zip](https://github.com/user-attachments/files/16355382/2024-07-24.01-59-04.zip)

**Comment by logslmao** [comment]
i would've told you what to do but because of a reason that sounds hateful towards myself and others i would rather not say it

**Comment by craftablescience** [comment]
You're mixing up VTF and VPK. That is a texture file.

**Comment by craftablescience** [comment]
I will eventually make an application that can open any generic Valve format, but now is not that day - VPKEdit can only open archives such as maps (BSPs) or VPKs

**Comment by craftablescience** [comment]
You can use [this application](https://github.com/Trico-Everfire/VTF_Edit_Revitalized) to open VTFs on Linux

**Comment by logslmao** [comment]
i actually dont know how to compile this but i'll figure it out myself

**Comment by craftablescience** [comment]
It has published releases, they're marked as prerelease so they won't show as releases on the main page

**Comment by logslmao** [comment]
sorry for asking this but how do i execute it?

**Comment by craftablescience** [comment]
Download the executable from the releases page and run it
