### ISSUE TITLE
Drag and drop to open files when no file is open

### ISSUE THREAD

**Issue by Cynosphere** [craftablescience/VPKEdit#159]
### Describe Your Suggestion

Currently drag and drop is only reserved for adding files to a VPK, but it would be nice to open VPKs via drag and drop if one isn't open.

**Comment by craftablescience** [comment]
Perhaps it could ask the user what they'd like to do in this scenario? There's a valid reason why someone might want to add a pack file to another, for example adding a BSP to a VPK
