### ISSUE TITLE
Arrow keys should control entry tree selection

### ISSUE THREAD

**Issue by boxden** [craftablescience/VPKEdit#16]
In the current `version 3.3.5` win64.
When using the "down arrow" and "up arrow" keys on the keyboard, there is no switching between textures in the preview. 
Texture preview only works when clicked with the mouse. 
This complicates navigation and limits the convenience of using the viewer.

https://github.com/craftablescience/VPKEdit/assets/30258996/b57abaef-8a0d-42da-a727-528eecca35c0

**Comment by craftablescience** [comment]
This is a good suggestion and I'll look into it
