### ISSUE TITLE
SVG preview

### ISSUE THREAD

**Issue by Cynosphere** [craftablescience/VPKEdit#160]
### Describe Your Suggestion

Panorama uses SVGs (`.svg` in Source, `.vsvg_c` in Source 2) for some graphics. It would be nice to be able to preview them from within VPKEdit.

**Comment by craftablescience** [comment]
`.vsvg_c` will not work in VPKEdit because I don't parse Source 2 files - use [Source 2 Viewer](https://valveresourceformat.github.io/) instead
