### ISSUE TITLE
vpk file names do not support non-ascii characters

### ISSUE THREAD

**Issue by Starfelll** [craftablescience/VPKEdit#162]
### Describe the Bug

Open a vpk file with a filename containing non-ascii characters.

### To Reproduce

1. Rename vpk filename as: "测试_test.vpk" or "テスト_test.vpk"
2. Open file via menu.
3. The error message pops up:
Unable to load this file. Please ensure that a game or another application is not using the file.

### Operating System

Windows10

**Comment by craftablescience** [comment]
While I still want to fix this bug, please keep in mind the Source engine will not enjoy loading non-ascii filenames in a lot of cases

**Comment by craftablescience** [comment]
Having looked into this, this is almost impossible to fix with the way the library is currently written. Text encoding is a nightmare!!!! I will probably try to fix this at some point, but I can't make any guarantees. Closing as wontfix for now
