### ISSUE TITLE
Provide Windows 7 backwards compatibility

### ISSUE THREAD

**Issue by Psycho-A** [craftablescience/VPKEdit#165]
### Describe Your Suggestion

First, VPKEdit is a greatest tool I seen in its class! But please keep in mind that not all modders use 64-bit systems and Windows 10. The Source engine remains old-school engine, and still natively supports 32 bits (and even Windows XP mostly), which means that all native SDK tools may be used on any retro machine of latest 10-15 years. 

I know you will tell about "Qt6" - but I don't think it's good that the whole program depends on some framework's compatibility. Qt5 and Qt4 are functional enough to provide required user experience on all VPKEdit features.

**Comment by craftablescience** [comment]
Honestly I don't think I *can* make a 32-bit build by this point, but a Windows 7 build is still feasible

**Comment by Psycho-A** [comment]
> Honestly I don't think I _can_ make a 32-bit build by this point (exaggeration, the few reasons this is the case are surmountable but it would take a lot of effort for very little gain), but a Windows 7 build is still feasible

It would be nice even with 64 bits, so I'm really looking forward to this build, and I'll be very grateful, like many others!

**Comment by craftablescience** [comment]
- CLI now works fine on Win7
- GUI crashes immediately using [this version of Qt6 for Win7](https://github.com/crystalidea/qt6windows7), and I can't debug it because Win7's windbg is insanely hard to find nowadays. Can you test if https://github.com/i486/VxKex allows [this standalone build](https://github.com/user-attachments/files/16576127/VPKEdit-Windows-Standalone-GUI-msvc-Release.zip) to work? It doesn't seem to do anything in my VM, but my copy of Win7 is apparently missing a few updates it needs that I can't find online. If that works it would make my life much easier :trollface: and in theory it should support this application since it supports Qt6

**Comment by Psycho-A** [comment]
@craftablescience 
I know that Qt5 works just fine on Windows 7. May be is there quick way to backport tool to it?
As for "qt6windows7"... This is what I did for myself with the VPKEdit a month ago :) The only thing which made crashes for me, is the function "CreateFile2" which I hex-replaced to regular "CreateFileW" in VpkEdit.exe binary, and tool successfully started to me! Although I don't know how much is it correct and is there no other issues in functionality (but I didn't notice for now).

**Comment by craftablescience** [comment]
>  The only thing which made crashes for me, is the function "CreateFile2" which I hex-replaced to regular "CreateFileW" in VpkEdit.exe binary, and tool successfully started to me!

I've replaced that with CreateFileW in the latest version :3 (we love CMake hacks!!)

Unfortunately this tool is pretty dependent on Qt6, I dunno how feasible it would be to backport. Looks like qt6windows7 is the way to go

**Comment by Psycho-A** [comment]
> Unfortunately this tool is pretty dependent on Qt6, I dunno how feasible it would be to backport. Looks like qt6windows7 is the way to go

No worries, I also think that "qt6windows7" is a solution, at least temporarily. If it is possible to link release versions to it, it will be nice! There are also native 32-bit builds for qt6windows7. Maybe this will make it easier to create a 32-bit version of VpkEdit..?

**Comment by craftablescience** [comment]
Not doing 32-bit builds lol, Windows 7 is enough. There is absolutely no reason to use a 32-bit OS in 2024. I tried looking on the [Steam hardware survey](https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam) to find the usage of 32-bit OSes and they're not even listed anymore, despite Steam being a 32-bit program itself

**Comment by Psycho-A** [comment]
Okay.. When can we expect the next release (with this fixes and VTMB VPK support as well)?

**Comment by craftablescience** [comment]
Sorry, I've been busy improving the base libraries VPKEdit relies on. I wanted to add a few more features to the next build, it should come out by the end of the month at the latest.

**Comment by craftablescience** [comment]
[VPKEdit-Windows-Installer-Compatibility-msvc-Release.zip](https://github.com/user-attachments/files/17087851/VPKEdit-Windows-Installer-Compatibility-msvc-Release.zip)
[VPKEdit-Windows-Standalone-GUI-Compatibility-msvc-Release.zip](https://github.com/user-attachments/files/17087852/VPKEdit-Windows-Standalone-GUI-Compatibility-msvc-Release.zip)

Can you test if either of these are working for you? They launch in my VM but the VM has some rendering issues, presumably because it's in a VM

**Comment by Psycho-A** [comment]
> [VPKEdit-Windows-Installer-Compatibility-msvc-Release.zip](https://github.com/user-attachments/files/17087851/VPKEdit-Windows-Installer-Compatibility-msvc-Release.zip) [VPKEdit-Windows-Standalone-GUI-Compatibility-msvc-Release.zip](https://github.com/user-attachments/files/17087852/VPKEdit-Windows-Standalone-GUI-Compatibility-msvc-Release.zip)
> 
> Can you test if either of these are working for you? They launch in my VM but the VM has some rendering issues, presumably because it's in a VM

Works just fine! Thank you. Also I found that 20mb-sized "opengl32sw.dll" file affects nothing and successfully deleteable. What is it actually needed for?

**Comment by craftablescience** [comment]
1. That DLL is used for software rendering on systems that don't have working OpenGL drivers, you can delete it from your install if you want to.

2. I don't speak Russian, but I welcome contributions to the POEditor project. The link to it is in the readme file on this repository.

**Comment by Psycho-A** [comment]
> That DLL is used for software rendering on systems that don't have working OpenGL drivers, you can delete it from your install if you want to.

Which graphics cards have no OpenGL drivers for now? As I know, even integrated ones have them...

> I don't speak Russian, but I welcome contributions to the POEditor project. The link to it is in the readme file on this repository.

Okay, I'll watch and think about it!

**Comment by craftablescience** [comment]
> Which graphics cards have no OpenGL drivers for now? As I know, even integrated ones have them...

Crappy Intel iGPUs that have horrible OpenGL support use the DLL, as well as very old computers
