### ISSUE TITLE
Ability to open folders

### ISSUE THREAD

**Issue by flleeppyy** [craftablescience/VPKEdit#172]
### Describe Your Suggestion

Hiya, I'd like to be able to open a folder in VPK edit like a vpk file. I really don't want to pack a folder as a VPK then open it just to use the viewer tools.

**Comment by craftablescience** [comment]
This is mostly a duplicate of #72 but I'm going to leave it open since it's a bit different

**Comment by craftablescience** [comment]
![image](https://github.com/user-attachments/assets/47b2e7ab-a87e-44c0-a8f8-7056b1a5975a)

This is pretty cool, took like a half hour to implement lol

I'm not doing anything fancy like watching the folder for changes or letting users modify the contents yet, but its a start
