### ISSUE TITLE
Close Hotkey

### ISSUE THREAD

**Issue by sterno900** [craftablescience/VPKEdit#175]
### Describe Your Suggestion

can we get either ESC or CTRL+W to close the window ? (on windows)
may be useful on how a person implemented it: https://github.com/AlienCowEatCake/ImageViewer/issues/14

**Comment by craftablescience** [comment]
`Alt + F4` is the current keybind for closing the window. Is there a reason you'd like `Ctrl + W` to close it as well?

**Comment by craftablescience** [comment]
Actually I'll change it so this keybind closes the opened pack file, `Ctrl + X` was a poor choice and conflicts with the text editor now that editing is supported
