### ISSUE TITLE
CLI: finish implementing file tree preview

### ISSUE THREAD

**Issue by SmileyAG** [craftablescience/VPKEdit#178]
### Describe Your Suggestion

Reproduce: `vpkeditcli --file-tree pak0.pak`

At the moment the filelist is not sorted in alphabetical order, which is not good.
You can also add the **uncompressed** filesize before or after the filename, separated by comma.

**Comment by craftablescience** [comment]
What I really want is a tree view like this:

![image](https://github.com/user-attachments/assets/15221d63-cd5a-457d-930d-f1075f679784)

Displaying entry metadata after the name would be a nice touch as well

**Comment by craftablescience** [comment]
![image](https://github.com/user-attachments/assets/e44c33b4-1662-46b0-b6c6-8de8684d0ee4)

Looks pretty and runs very quickly
