### ISSUE TITLE
Files always been using

### ISSUE THREAD

**Issue by ZvZPvz** [craftablescience/VPKEdit#188]
### Describe the Bug

![image](https://github.com/user-attachments/assets/00d85b2d-17b0-47bf-a969-182cc64caa72)
File always shown as being in use, But I didn't open ANY application, and also the file is read/writeable

### To Reproduce

1. Open any vpkedit supported file
2. Notice that any file show "Failed to read file contents! Please ensure that a game or another application is not using the file."

### VPKEdit Version

4.2.3

### Operating System

Windows

**Comment by craftablescience** [comment]
I see you are using v4.2.3. That version has a known bug where it will corrupt maps saved with it. Please upgrade to the latest version of the software, I have fixed that.

**Comment by ZvZPvz** [comment]
I can open the file, but when i try to save it, it when display "No permission" or "Other app is using"

**Comment by craftablescience** [comment]
Have you updated the file since saving it with the broken VPKEdit version? It may still be corrupted
