### ISSUE TITLE
Can't extract CmdSeq.wc from dark messiah single player sdkbase.gcf.

### ISSUE THREAD

**Issue by ZachKnife1008** [craftablescience/VPKEdit#189]
### Describe the Bug

Whenever I try to extract CmdSeq.wc from dark messiah single player sdkbase.gcf (which can be found in [this download](https://www.moddb.com/games/dark-messiah-of-might-magic/downloads/dark-messiah-might-and-magic-sdk)), it doesn't extract the file out of the archive.

### To Reproduce

1. Open the specified archive in VPKEdit.
2. Try to extract the offending file in the _bin_ folder out of the archive.

### VPKEdit Version

4.3.2

### Operating System

Windows 11

**Comment by craftablescience** [comment]
Hm thanks for the report, will look into this

**Comment by craftablescience** [comment]
Turns out GCF filenames are case-sensitive but the current code treats them as case-insensitive, it was only 4 lines of code to fix 🙃

Will be fixed in the next release, in the meantime use GCFScape to extract GCFs
