### ISSUE TITLE
Can't open ANY VPK because "it's in use"

### ISSUE THREAD

**Issue by An-Untitled-Developer** [craftablescience/VPKEdit#191]
### Describe the Bug

The vpk's are from titanfall 2, I only have VPKEdit open. Steam nor the EA App is running in the background.

### To Reproduce

No clue. It's just doing it.

### VPKEdit Version

4.3.2

### Operating System

Windows 11

**Comment by craftablescience** [comment]
VPKEdit doesn't support Titanfall 1/2 VPKs yet

**Comment by An-Untitled-Developer** [comment]
damn
