### ISSUE TITLE
Add preview widget for models

### ISSUE THREAD

**Issue by craftablescience** [craftablescience/VPKEdit#21]
Just a simple wireframe of the model since we don't have the shaders or possibly the materials for it, maybe add an option to toggle the collision model wireframe too

After that's done it might be neat to at least try loading the model skins and textures if we find them in the VPK, to have a very rudimentary textured preview (and have an option for that too)

**Comment by ashifolfi** [comment]
I think only wireframe would make some models impossible to interpret by sight.

Two options that could work better in terms of a simple method to display that still makes it possible to know what you're looking at:

1. Basic shader that has one light and a solid white/gray base color on the model (most game engines do something like this for a default material)
2. Placing a wire frame on top of a solid color. (I.e. the wireframe looks like a "texture" on the model.

Both of these would be good for readability.

**Comment by craftablescience** [comment]
Oh so like how Blender works, that sounds a lot better
