### ISSUE TITLE
Support for reading/writing BSP paklump

### ISSUE THREAD

**Issue by ertup0** [craftablescience/VPKEdit#27]
It says that this program has all capabilites of GCFScape but for some reason it doesn't support opening BSP files and view embedded files.
Is this feature out of scope?

**Comment by craftablescience** [comment]
I should probably remove that from the readme tbh, this program is never going to support reading some of the formats gcfscape can, like gcf files
That being said, parsing bsps and editing their pack lumps would be a great feature, and I would like to implement that at some point. The challenge is abstracting it without changing the existing code too much
