### ISSUE TITLE
Add file association on Linux

### ISSUE THREAD

**Issue by HurricanePootis** [craftablescience/VPKEdit#30]
Howdy,

I am the current AUR maintainer for `vpkedit` and `vpkedit-git`. On those packages, I add in file associations for vpk files, and make it where vpkedit can auto open them.

# What is needed for file assocation
On linux, you need at least a few things to get file assocation. First, you need a xml file at `/usr/share/mime/packages/vpkedit.xml` which defines basaically what a VPK is, what extension do vpk files use, and what icon should vpk files have. 
## Defining what a VPK is
Currently, in my PKGBUILD, I have the following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
    <mime-type type="application/x-vpk">
    <comment>VPK Archive</comment>
<icon name="x-vpk"/>
<acronym>VPK</acronym>
<expanded-acronym>Valve Pack File</expanded-acronym>
    <glob-deleteall/>
    <glob pattern="*.VPK"/>
    <glob pattern="*.vpk"/>
    </mime-type>
</mime-info>
```
This defines a new mime `application/x-vpk`, gets it the icon name `x-vpk`, expands the acronym, adds a comment you will see whenever hovering over the file, and adds the patern to look out for.
## An icon for VPKs
In my PKGBUILD, I copy the `vpkedit.png` installed at `/usr/share/pixmaps/vpkedit.png` to `/usr/share/icons/hicolor/128x128/mimetypes/x-vpk.png`. Since VPK's are defined above to have the icon named `x-vpk`, it will use that `x-vpk.png` as its icon now.
## Associating VPKEdit with the VPK file
To get vpkedit to be associated with vpks now, you have to add the `MimeType` option to the .desktop file for vpkedit. Currently, my PKGBUILD makes it so the the desktop file ends up looking like this:
```
[Desktop Entry]
Version=3.6.0
Name=VPKEdit
Comment=A tool to read, preview, and write to VPK files.
Exec=/opt/vpkedit/vpkedit %f
Icon=vpkedit
Terminal=false
Type=Application
Categories=Qt;Development;Utility;
MimeType=application/x-vpk
```
I associated it with `application/x-vpk`, and added a `%f` as per the [freedesktop desktop file spec](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html); gives file argument.

# That's Basically It
Yeah, just those three things give you the glorious ability to double click on a vpk. Honestly, I am making this issue to let you know about it, and hopefully get this implemented upstream. I would make a pull request, but I don't know how to do anything with cmake.

**Comment by craftablescience** [comment]
Thank you for this extensive issue, as soon as I'm not busy I'll add this in :)
I was initially trying to add extensions but couldn't figure it out, and subsequently forgot about it

**Comment by HurricanePootis** [comment]
Not a problem!

**Comment by craftablescience** [comment]
![Screenshot_20231209_012347](https://github.com/craftablescience/VPKEdit/assets/26600014/0c944702-949e-4d6f-88af-d0b94dd318f8)

Looks like it's working, tysm! This will be in the next release

**Comment by HurricanePootis** [comment]
Swag thank you
