### ISSUE TITLE
Add up folder and back/forward buttons

### ISSUE THREAD

**Issue by vrad-exe** [craftablescience/VPKEdit#34]
Add a navigation bar with buttons to go forward/back and up one folder. Currently these are missing which makes navigation feel clunky compared to other tools like GCFScape. The forward/back buttons should also be mapped to the mouse side buttons if present.

**Comment by craftablescience** [comment]
Why mouse side buttons? I don't have a mouse with more than 3 buttons, do other tools do this?

**Comment by AWildErin** [comment]
GCFScape does it. It's a nice bind to have, especially if you have muscle memory for it

**Comment by craftablescience** [comment]
Alright
