### ISSUE TITLE
File/folder sort order is inconsistent

### ISSUE THREAD

**Issue by vrad-exe** [craftablescience/VPKEdit#36]
The sort order of files and folders is inconsistent between the left and right columns: the right column uses the Windows style where folders are always sorted above files, but the left column doesn't and mixes them together. This makes navigation somewhat confusing since folders will appear in different places between the two columns.

I'd suggest adding a setting to choose between the Windows and non-Windows styles, and make both columns use the selected mode.

**Comment by craftablescience** [comment]
Sort order should not be inconsistent, I thought I already fixed this?
![image](https://github.com/craftablescience/VPKEdit/assets/26600014/169f57fd-4f8c-430c-8aa5-7daca1d430d0)

**Comment by vrad-exe** [comment]
Oh I was on an old version
