### ISSUE TITLE
Add some more CLI features

### ISSUE THREAD

**Issue by craftablescience** [craftablescience/VPKEdit#43]
- [x] When packing, control preload amount of specific file types
- [x] Convert VPK into directory (extract)
- [x] Add files to VPK
- [x] Extract individual files/directories from VPK
- [x] Remove files from VPK
- [x] Print VPK directory tree to console
- [x] Verify integrity of VPK (checksums / signature)

**Comment by Nbc66** [comment]
> * [ ]  Print file to console without saving

Could posibly have a --dry-run argument and just simulate the output vpk structer

Example:
```
vpkeditcli -o whaterver_dir.vpk --dry-run

The vpk will be structured as follows
Root/
 materials/
    File_1.vtf
    Folder/
      File2.vtf

**Comment by NvC-DmN-CH** [comment]
If you add support for extracting individual files, this would singlehandedly allow me to release my tool lol, I use a tool for vpk files written in python, but I don't want to rely on python

I'm making a very useful tool imo: it hooks into hammer, and when you press a shortcut, it looks what the currently selected prop is, and exports it to blender. You can compile it back in blender with pressing a button, and when you go back to hammer you see it changed. Can also compile a model as an unique one, affecting only the selected prop. And also has a functionality to combine multiple selected props into 1.

So um, I'm explaining this to hopefully make you as excited as I am about this thingy and give you motivation to update the cli!

**Comment by craftablescience** [comment]
Oh that's sick, I can get this done

**Comment by craftablescience** [comment]
I'm really tired so I'm going to sleep now, and I have an event tomorrow after I wake up that will take a few hours. If I don't get this done in the next 24 hours make a callout post on my Twitter.com (just bump this thread, probably won't forget though)

**Comment by NvC-DmN-CH** [comment]
Oh it's okay, no need for urgency! It's going to take a couple of weeks for me to get my tool into a stable state.
Really appreciate what you do

**Comment by craftablescience** [comment]
Woops I've put this on the backlog for way too long

**Comment by craftablescience** [comment]
Extraction done

**Comment by NvC-DmN-CH** [comment]
> Extraction done

omg


does the release for the CLI have this change?

**Comment by craftablescience** [comment]
I'm not cutting a release until I finish checking off this whole list, but here's the standalone binaries:
[VPKEdit-Linux-Standalone-CLI-gcc-Release.zip](https://github.com/user-attachments/files/15872436/VPKEdit-Linux-Standalone-CLI-gcc-Release.zip)
[VPKEdit-Windows-Standalone-CLI-msvc-Release.zip](https://github.com/user-attachments/files/15872447/VPKEdit-Windows-Standalone-CLI-msvc-Release.zip)

**Comment by craftablescience** [comment]
This is finally done, release will be up in under an hour
