### ISSUE TITLE
VPKEdit CLI has missing dependencys or im just a idiot with linux

### ISSUE THREAD

**Issue by Nbc66** [craftablescience/VPKEdit#45]
```./vpkeditcli: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./vpkeditcli)```

this is what it says its missing

**Comment by craftablescience** [comment]
Try running:
```sh
sudo apt update
sudo apt install libstdc++6
```

**Comment by Nbc66** [comment]
still missing that version here is the output using strings

```
root@localhost:~# strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_DEBUG_MESSAGE_LENGTH
```

**Comment by craftablescience** [comment]
Ah just one off
Can I ask what distro and version you're running?

**Comment by Nbc66** [comment]
here is the os-release files output

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
```

**Comment by Nbc66** [comment]
im going to upgrade to Debian 12 and test it out

**Comment by craftablescience** [comment]
I've been looking for a way to upgrade that package for Debian 11, but updating to Debian 12 would definitely fix it
I run that on my laptop that I use for Linux testing

**Comment by Nbc66** [comment]
It Works on Debian 12

**Comment by craftablescience** [comment]
The application relies on modern C++ features, and frankly I don't know Linux well enough to see if I can get it to run with older glibcxx versions, so I'm going to mark this as a wontfix
