### ISSUE TITLE
Packing a VPK with a relative path upsets the packer

### ISSUE THREAD

**Issue by Nbc66** [craftablescience/VPKEdit#46]
here is an image of it in gcfscape

![GCFScape_e8dTfxkWGC](https://github.com/craftablescience/VPKEdit/assets/34843947/65956cd2-bc53-4f9c-9412-0bba6fd9cf41)

Ideally it should just make the path be the materials or whatever

like when i do ```vpkeditcli -o game_materials_dir.vpk  ./materials```

it should ideally make the vpk path be ```materials/```

when i open the dir.vpk in gcf scape

**Comment by craftablescience** [comment]
That makes sense, I can change that and add a flag to enable the old behavior

**Comment by Nbc66** [comment]
yes please if you can

**Comment by craftablescience** [comment]
Did some digging and the current way it works is actually how Valve's vpk CLI tool works, so here's a compromise:
- If one path is given, it will pack its contents under the root folder unless a flag is set (I'm thinking `-S` / `--subroot`)
- If multiple paths are given, it will pack them under the root folder and require an output name to be explicitly passed

**Comment by craftablescience** [comment]
I'm dumb I just realized what the issue was actually talking about
