### ISSUE TITLE
Add a warning when saving a multichunk VPK without a "_dir" suffix

### ISSUE THREAD

**Issue by Nbc66** [craftablescience/VPKEdit#48]
when creating the output vpks and specifying the name of the actual output vpk when naming the vpk the file cant be opend in a vpk viewer unless we name the output vpk ```whatever_dir.vpk```

NOTE: the ```whaterver_dir.vpk``` doesnt actualy need to be named ```whatever_dir.vpk``` but it needs to have ```_dir``` at the end of the file

**Comment by Nbc66** [comment]
could just force add _`_dir`_ to the end of the filename but then again you can just tell people to actualy just specify ```_dir``` if they are trying to create a vpk using -o

**Comment by craftablescience** [comment]
This is a required VPK feature, directory VPKs (VPKs that reference numbered archives) will always end in `_dir`
I will add a warning to the console

**Comment by craftablescience** [comment]
I pushed a new release with the fixes to the issues you've been reporting (thanks for that btw! much appreciated)
