### ISSUE TITLE
Proposal: adding vpkedit to winget the windows package manager

### ISSUE THREAD

**Issue by Nbc66** [craftablescience/VPKEdit#52]
Would be cool to add the vpkedit client to the windows pacakge manager

Here is the official guid that windows gives on how to add packages to winget

https://learn.microsoft.com/en-us/windows/package-manager/package/repository

**Comment by Nbc66** [comment]
Apt would be also cool but idk how hard it is to add it to apt

**Comment by craftablescience** [comment]
> Apt would be also cool but idk how hard it is to add it to apt

It is possible to create a self-hosted apt repository and distribute updates over that, I was actually looking into it earlier. I will probably set one up at some point before 4.0 releases

**Comment by craftablescience** [comment]
Created a PR to add it to winget, unfortunately the installer is incorrectly marked as a trojan by Microsoft and Microsoft alone (ran it through virustotal, 1/64 services mark it as a virus... 😭), so the submission process will probably be delayed until they fix that (*if* they fix that, I'm no big company)

**Comment by craftablescience** [comment]
> The file submitted for malware analysis has been added to the queue. Depending on the prevalence of the file and its potential impact, we will prioritize its analysis appropriately.

I will be surprised if they review this file before a month is up

**Comment by Nbc66** [comment]
Yeah idk why winodws likes to mark some stuff as mallware if its not even mallaware 

False positives happen they will probably review it manually on winget

**Comment by Nbc66** [comment]
on another note i found this today for making ppa's using github itself

https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html

**Comment by craftablescience** [comment]
![image](https://github.com/craftablescience/VPKEdit/assets/26600014/76b7aaff-6931-40cf-a8a7-ed0074b4acf4)

winget submission completed successfully 🎉

**Comment by Nbc66** [comment]
Thats ammazing thank you
