### ISSUE TITLE
Adding some keyboard shortcuts

### ISSUE THREAD

**Issue by Scipply** [craftablescience/VPKEdit#59]
### Describe Your Suggestion

I am so used to using del or X for deleting bc most programs have that feature and I thought you might want to add it. Maybe you could also add some other shortcuts to make it faster to use like shift + a after selecting a directory in the file list to add a file in that dir, backspace to go back/up one directory, 1/2/3/4 in 3d preview to change the render mode.

**Comment by craftablescience** [comment]
> backspace to go back/up one directory
> 1/2/3/4 in 3d preview to change the render mode

these are already implemented, update your installation

**Comment by craftablescience** [comment]
Implemented using the `Delete` key to remove selected entries

As for the first suggestion, that's already a keybind:
![image](https://github.com/craftablescience/VPKEdit/assets/26600014/73122740-325b-4901-86f7-c40b9a92349c)

I will add a controls reference so its easier to learn the application's shortcuts
