### ISSUE TITLE
Crash: Program crashes when attempting to load a material in-use by a game or hammer

### ISSUE THREAD

**Issue by Equalizer5118** [craftablescience/VPKEdit#6]
The title is self-explanatory. If you open the vpk of a game that is running (or is in use by Hammer) and then try to preview a material, the program will crash. This was tested on the Windows standalone 3.1.1 version, and with P2CE hammer+game open when attempting to open a material in `Portal 2/portal2/pak01_dir.vpk`. There is no error message; the program freezes for a second and then abruptly crashes.

### Expected behaviour
The program should prevent the material from being opened if in use and the material should be grayed out in the browser, like how GCFScape does this.

**Comment by craftablescience** [comment]
I actually pushed a fix for this recently, I'll publish a new release

**Comment by craftablescience** [comment]
the fix was half-baked so I made a proper one, fixed in 154892ac2b0947b95746b8da2d451cadf56dbfab (v3.2.0)
