### ISSUE TITLE
pack a file as an archive(_xxx.vpk yk) checkbox is reversed

### ISSUE THREAD

**Issue by Scipply** [craftablescience/VPKEdit#60]
### Describe the Bug

Importing a file into vpkedit brings up the pop up which has an option to put the file into an archive. Well that option is lying and it does the opposite. I dont know how nobody noticed that(if that happens to others too) but if it somehow happens bc of the config I was using, here it is: the theme was modern dark mode, vpk version was 1 and I was on the latest version as of 2 weeks ago

### To Reproduce

1. import file
2. check/uncheck the only checkbox there is
3. import and save

Congrats! Now the file ended up packed the opposite of how you wanted.

### Operating System

windows 10 (probably irelevant)

**Comment by craftablescience** [comment]
Fixed in the next release, sorry about that
