### ISSUE TITLE
Selecting a non "_dir" vpk should be able to find the associated _dir vpk, instead of throwing an error

### ISSUE THREAD

**Issue by ElliotElison** [craftablescience/VPKEdit#62]
### Describe Your Suggestion

VRF is able to do this, it makes opening vpks a tiny bit faster.

**Comment by ElliotElison** [comment]
Was there a PR associated with this?

**Comment by craftablescience** [comment]
I just pushed directly to main, it was like 3 lines

**Comment by craftablescience** [comment]
I made a pr for the other one because I needed to test it on my Linux laptop
