### ISSUE TITLE
Hotkeys for changing the viewport mode when previewing a model

### ISSUE THREAD

**Issue by ElliotElison** [craftablescience/VPKEdit#65]
### Describe Your Suggestion

It would be nice to have hotkeys to change the viewport mode between textured, textured-shaded, wireframe, etc. Maybe just one hotkey to cycle between them?

**Comment by craftablescience** [comment]
This exists, its keys 1-4, leaving this issue open because a singular key to cycle the modes would also be nice

**Comment by ElliotElison** [comment]
Ah cool, might be good to have a hotkeys menu in the program too so I can check what already exists.

**Comment by craftablescience** [comment]
Already added in code, just not in a release yet - check CONTROLS.md at the repo root

**Comment by craftablescience** [comment]
> leaving this issue open because a singular key to cycle the modes would also be nice

would be nice but for some reason Qt doesn't like this idea, I think the existing hotkeys are probably enough
