### ISSUE TITLE
Different icons for different file types

### ISSUE THREAD

**Issue by ElliotElison** [craftablescience/VPKEdit#66]
### Describe Your Suggestion

Would be nice to have an icon next to the file, perhaps taken from the windows program-file type association, to more easily differentiate files in the list.

**Comment by craftablescience** [comment]
Thanks for making this suggestion, it looks awesome! Can't believe I didn't think of this

![image](https://github.com/craftablescience/VPKEdit/assets/26600014/fff7a7d3-f9fc-436e-8d63-39e788c7b013)

**Comment by ElliotElison** [comment]
Looks great! Exactly what I was imagining.
