### ISSUE TITLE
Create workflow to automate WinGet releases

### ISSUE THREAD

**Issue by Nbc66** [craftablescience/VPKEdit#77]
### Describe Your Suggestion

As the title says just automating the process of uploading new builds to winget and the personal ppa for VPKEdit

Not sure about how you can do it on winget there is probably a bot that can auto make pull requests for the winget repo

**Comment by Nbc66** [comment]
ok looks like the winget package creator allready can be used with ci/cd pipelines

https://github.com/microsoft/winget-create?tab=readme-ov-file#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline

**Comment by craftablescience** [comment]
Splitting up this issue into two as PPA releases are both way easier to do manually than WinGet releases and much harder to automate, so there's less of an incentive to get that done
