### ISSUE TITLE
Create minidumps on crash on Windows

### ISSUE THREAD

**Issue by craftablescience** [craftablescience/VPKEdit#86]
### Describe Your Suggestion

Would be helpful for debugging crashes people get

**Comment by Nbc66** [comment]
https://learn.microsoft.com/bs-latn-ba/windows/win32/api/minidumpapiset/nf-minidumpapiset-minidumpwritedump?redirectedfrom=MSDN

Reference for minidumps on windows

**Comment by Nbc66** [comment]
On another note you could also use sentey.io but im not sure if it creates local crashdumps you can debug

https://docs.sentry.io/platforms/native/guides/minidumps/

**Comment by craftablescience** [comment]
I'm gonna be honest I don't think this is super necessary, I haven't gotten a crash report in ages
