### ISSUE TITLE
Standalone Version Saves Settings to Registry on Windows

### ISSUE THREAD

**Issue by Hazbelll** [craftablescience/VPKEdit#9]
### Description
On Windows, if you execute/modify the settings of the standalone version of VPKEdit, its settings will be saved to the registry at `HKEY_CURRENT_USER\SOFTWARE\craftablescience\vpkedit`. It would be better if they were saved alongside the executable file (`vpkedit.exe`) to retain easy portability.

### Reproduction
1. Execute the standalone version of VPKEdit.
2. Modify the application's settings.
3. Open the Windows Registry Editor.
4. Note the settings chosen are saved into `HKEY_CURRENT_USER\SOFTWARE\craftablescience\vpkedit`

**Comment by craftablescience** [comment]
Thanks for the suggestion, fixed as of 3e47fd4fc99c520342a27a8f7a6d318dddc88b9b (v3.3.1)
