### ISSUE TITLE
Add keyboard shortcuts to navigate in entry tree

### ISSUE THREAD

**Issue by Sergueille** [craftablescience/VPKEdit#94]
### Describe Your Suggestion

* `Up Arrow` and `Down Arrow`: select the file above or under the selected file in the list
* `Right Arrow`: if a folder is selected, expand it and select it's first element

If this is too confusing, add a modifier key like `Ctrl`

**Comment by Sergueille** [comment]
I would be happy to try changing this myself, but it will take some time...

**Comment by craftablescience** [comment]
This is already implemented in code, it broke in 4.0

**Comment by craftablescience** [comment]
(and has since been patched)
