### ISSUE TITLE
Model viewer is missing

### ISSUE THREAD

**Issue by sumdudinhell** [craftablescience/VPKEdit#96]
### Describe the Bug

When I try to open a .mdl file, the model viewing toolbar appears, but no model is shown, even when I change modes (for example to wireframe). VTF viewing works fine though.

### To Reproduce

1. Open VPKEdit
2. Open a .mdl file inside my desired .vpk file
3. where model!1!1!1!1!
![screenshot-0cff74bc](https://github.com/craftablescience/VPKEdit/assets/152049532/cf214b95-f0bb-4ffc-8307-7c2a1beea1ab)

### Operating System

Arch Linux, LXQt as desktop, VPKEdit latest release (not from the AUR)

**Comment by craftablescience** [comment]
The Linux build seems a bit cursed on non-Debian distros yikes

Going to make a separate issue for converting those top buttons to icons instead of Unicode characters

**Comment by craftablescience** [comment]
Also, have you checked the model isn't just offscreen?

**Comment by craftablescience** [comment]
> > Also, have you checked the model isn't just offscreen?
> 
> i have, it didn't work, i just moved my mouse around with no model popping up. also tried maximizing, it also didn't work

The reason I ask is because c_hands are usually pretty far offset from the origin. If you could test a different model, like a regular prop, that would be fantastic
